config/routes.rb
Rails.application.routes.draw do
  get "/invites/:id_bet/novo" => "invites#novo", as: "novo_invite"
  get "/invites/inserir" => "invites#inserir", as: "inserir"
  resources :invites
  resources :guesses
  resources :bets
  get "/apostas/nova" => "bets#nova"
  post "/apostas/nova" => "bets#bet_create"
  get "/apostas/inside_bet" => "bets#inside_bet"
  post "/apostas/inside_bet" => "bets#inside_bet"
  get "/bets/" => "bets#inside_bet"
  get "/guesses/nova" => "guesses#nova"
  post "/guesses/nova" => "guesses#guess_create"
  post "/usuarios/login" => "usuarios#login"
  get "/usuarios/cadastro" => "usuarios#cadastro"
  get "/painel" => "welcome#painel"
  get "/usuarios_srch" => "invites#usuarios_srch", as: 'usuarios_srch'
  post "/usuarios/cadastro" => "usuarios#cadastro_create"
  resources :usuarios
  get "/auth/:provider/callback" => "sessions#create", as: :auth_callback
  get "/auth/failure" => "sessions#failure", as: :auth_failure
  get "/logout" => "sessions#destroy", as: :logout
  get 'welcome/index'
  resources :widgets
  get "/apostas/minhas" => "bets#lista"

  root 'welcome#index'
  
  resources :dialogos do
    resources :postagems
end

end

app/models/invite.rb
class Invite < ActiveRecord::Base
    validates :id_bet, :id_user, presence: true
    belongs_to :bet, class_name: 'Bet', foreign_key: 'id_bet'
    belongs_to :usuario, class_name: 'Usuario', foreign_key: 'id_user'
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  before_action :set_invite, only: [:show, :edit, :update, :destroy]

  # GET /invites
  # GET /invites.json
  def index
    @invites = Invite.where(id_user: session[:user_id])
  end

  # GET /invites/1
  # GET /invites/1.json
  def show
  end
  
  # Campo de Busca
  def usuarios_srch
    @selected = Usuario.all
    @bets = Bet.find(params[:id_bet])
    @search = params[:search]
    
    if params[:search]
      @selected = Usuario.search(params[:search])
      
      if params[:search]==""
        @selected = nil
      end
    else
      @selected = nil
    end
    
    respond_to do |format|
      format.js
    end
  end

  # GET /invites/new
  def new
    @invite = Invite.new
    @usuarios = nil
  end
  
  # GET /invites/1/novo
  def novo
    @usuarios = nil
  end
  
  #GET /invites/inserir
  def inserir
    convite = Invite.new
    
    convite.id_bet = params[:id_bet]
    convite.id_user = params[:id_user]
    
    convite.save
    
    #Dar reload nos contatos
    redirect_to usuarios_srch_path(:search => params[:search], :id_bet => params[:id_bet])
    
  end

  # GET /invites/1/edit
  def edit
  end

  # POST /invites
  # POST /invites.json
  def create
    @invite = Invite.new(invite_params)

    respond_to do |format|
      if @invite.save
        format.html { redirect_to @invite, notice: 'Invite was successfully created.' }
        format.json { render :show, status: :created, location: @invite }
      else
        format.html { render :new }
        format.json { render json: @invite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invites/1
  # PATCH/PUT /invites/1.json
  def update
    respond_to do |format|
      if @invite.update(invite_params)
        format.html { redirect_to @invite, notice: 'Invite was successfully updated.' }
        format.json { render :show, status: :ok, location: @invite }
      else
        format.html { render :edit }
        format.json { render json: @invite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invites/1
  # DELETE /invites/1.json
  def destroy
    @invite.destroy
    respond_to do |format|
      format.html { redirect_to invites_url, notice: 'Invite was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invite
      @invite = Invite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invite_params
      params.require(:invite).permit(:id_bet, :id_user)
    end
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/views/invites/_form.html.erb
<%= form_for(@invite) do |f| %>
  <% if @invite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invite.errors.count, "error") %> prohibited this invite from being saved:</h2>

      <ul>
      <% @invite.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_bet %><br>
    <%= f.number_field :id_bet %>
  </div>
  <div class="field">
    <%= f.label :id_user %><br>
    <%= f.number_field :id_user %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/invites/_preview.html.erb
<div id="usuarios">
    <%= render partial: 'usuarios_list', locals: {usuarios: usuarios, id_aposta: id_aposta, search: ""} %>
</div>

app/views/invites/_usuarios_list.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
        <h2 class="panel-title"><span class="glyphicon glyphicon-list"></span>&nbsp;Resultados da Busca</h2>
    </div>
    <div class="panel-body">
        <% if usuarios != nil and usuarios.count >= 1 %>
            <table class="table table-hover">
              <% usuarios.each do |f| %>
                <tr>
                  <td>
                    <%= f.name %>
                  </td>
                  <td class="text-right">
                    <% @convite = Invite.where("id_bet = ? AND id_user = ?", id_aposta, f.id) %>
                    <% if @convite.count >= 1 %>
                        <span class="glyphicon glyphicon-ok"></span>&nbsp;Convidado
                    <% else %>
                        <%= link_to inserir_path(:search => search, :id_bet => id_aposta, :id_user => f.id), :remote => true do%>
                            <span class="glyphicon glyphicon-envelope"></span>&nbsp;Convidar
                        <% end %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </table>
        <% else %>
            <p>Sua busca não retornou resultados...</p>
        <% end %>
    </div>
</div>

app/views/invites/edit.html.erb
<h1>Editing Invite</h1>

<%= render 'form' %>

<%= link_to 'Show', @invite %> |
<%= link_to 'Back', invites_path %>

app/views/invites/index.html.erb
<%= render "layouts/header" %>
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-lg-10">

    <legend>Apostas que fui convidado a participar</legend>
    
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Nome da Sala</th>
          <th>Descrição</th>
          <th>Dono da Sala</th>
          <th>Categoria</th>
          <th>Data limite para apostas</th>
          <th></th>
        </tr>
      </thead>
    
      <tbody>
        <% @invites.each do |invite| %>
          <tr>
            <% aposta = Bet.find(invite.id_bet) %>
            <% dono = Usuario.find(aposta.usuario_id) %>
            <td><%= aposta.name %></td>
            <td><%= aposta.description %></td>
            <td><%= dono.name %></td>
            <td><%= aposta.category %></td>
            <td>
                <% if aposta.final_date != nil %> 
                  <%= aposta.final_date.strftime "%d/%m/%Y" %>
                <% end %>
            </td>
            <td>
                <%= link_to controller: "bets", action:'inside_bet', :id => invite.id_bet do %>
                  <span class='glyphicon glyphicon-log-in'></span>
                <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    
  </div>
</div>

<%= render "layouts/footer" %>

app/views/invites/new.html.erb
<h1>New Invite</h1>

<%= render 'form' %>

<%= link_to 'Back', invites_path %>

app/views/invites/novo.html.erb
<%= render "layouts/header" %>

    <legend>Convidar Amigos</legend>
        Digite o nome do convidado na caixa de busca para pesquisar. Clique em "Convidar" para efetuar o convite<br>
        <div class="row">
            <div class="col-lg-6">
                
                <%= form_tag usuarios_srch_path, :method => 'get', :id => "search_form", :remote => true do %>
                    <%= text_field_tag :search, params[:search], class: "form-control" %>
                    <%= hidden_field_tag :id_bet, params[:id_bet] %>
                <% end %>
                
                <br>
                
                <div id="usuarios">
                    <%= render partial: 'preview', locals: {usuarios: @usuarios, id_aposta: params[:id_bet], search: ""} %>
                </div>
            
            </div>
    </div>
    <%= link_to 'Back', invites_path %>

<%= render "layouts/footer" %>

app/views/invites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id bet:</strong>
  <%= @invite.id_bet %>
</p>

<p>
  <strong>Id user:</strong>
  <%= @invite.id_user %>
</p>

<%= link_to 'Edit', edit_invite_path(@invite) %> |
<%= link_to 'Back', invites_path %>

app/views/invites/usuarios_srch.js.erb
$("#usuarios").html("<%= escape_javascript(render partial: 'usuarios_list', locals: { usuarios: @selected, id_aposta: @bets.id, search: @search } ) %>");