config/routes.rb
Rails.application.routes.draw do
  get "/invites/:id_bet/novo" => "invites#novo", as: "novo_invite"
  get "/invites/inserir" => "invites#inserir", as: "inserir"
  resources :invites
  resources :guesses
  resources :bets
  get "/apostas/nova" => "bets#nova"
  post "/apostas/nova" => "bets#bet_create"
  get "/apostas/inside_bet" => "bets#inside_bet"
  post "/apostas/inside_bet" => "bets#inside_bet"
  get "/bets/" => "bets#inside_bet"
  get "/guesses/nova" => "guesses#nova"
  post "/guesses/nova" => "guesses#guess_create"
  post "/usuarios/login" => "usuarios#login"
  get "/usuarios/cadastro" => "usuarios#cadastro"
  get "/painel" => "welcome#painel"
  get "/usuarios_srch" => "invites#usuarios_srch", as: 'usuarios_srch'
  post "/usuarios/cadastro" => "usuarios#cadastro_create"
  resources :usuarios
  get "/auth/:provider/callback" => "sessions#create", as: :auth_callback
  get "/auth/failure" => "sessions#failure", as: :auth_failure
  get "/logout" => "sessions#destroy", as: :logout
  get 'welcome/index'
  resources :widgets
  get "/apostas/minhas" => "bets#lista"

  root 'welcome#index'
  
  resources :dialogos do
    resources :postagems
end

end

app/models/bet.rb
class Bet < ActiveRecord::Base
    
    validates :name, :usuario_id, :category, :room_status, :room_type, :stake, presence: true
    
    belongs_to :usuario, class_name: 'Usuario', foreign_key: 'usuario_id'
    #os testes de tipo de campo sao garantidos pela gema
    
    has_many :guesses
    has_many :invites
end

app/controllers/bets_controller.rb
class BetsController < ApplicationController
  before_action :set_bet, only: [:show, :edit, :update, :destroy, :inside_bet]

  # GET /bets
  # GET /bets.json
  def index
    @bets = Bet.all
  end

  # GET /bets/1
  # GET /bets/1.json
  def show
  end

  # GET /bets/new
  def new
    @bet = Bet.new
  end

  # GET /bets/1/edit
  def edit
  end

  # POST /bets
  # POST /bets.json
  def create
    @bet = Bet.new(bet_params)

    respond_to do |format|
      if @bet.save
        format.html { redirect_to @bet, notice: 'Bet was successfully created.' }
        format.json { render :show, status: :created, location: @bet }
      else
        format.html { render :new }
        format.json { render json: @bet.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def nova
  	@bet = Bet.new
  end
  
  def inside_bet
    #render:inside_bet 
  end
  
  
  def bet_create
  	@bet = Bet.new(bet_params)
    @bet.usuario_id = session[:user_id]
    @bet.category = 'Personalizado'
    @bet.room_status = 1
    
    respond_to do |format|
      if @bet.save
        format.html { render:inside_bet }
        #format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render:nova }
        format.json { render json: @bet.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def lista
    myBets
  end
  
  def myBets
    @bets = Bet.where(usuario_id:  session[:user_id])
  end
  

  # PATCH/PUT /bets/1
  # PATCH/PUT /bets/1.json
  def update
    respond_to do |format|
      if @bet.update(bet_params)
        format.html { redirect_to @bet, notice: 'Bet was successfully updated.' }
        format.json { render :show, status: :ok, location: @bet }
      else
        format.html { render :edit }
        format.json { render json: @bet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bets/1
  # DELETE /bets/1.json
  def destroy
    @bet.destroy
    respond_to do |format|
      format.html { redirect_to bets_url, notice: 'Bet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bet
      @bet = Bet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bet_params
      params.require(:bet).permit(:name, :description, :usuario_id, :url_photo, :category, :room_status, :room_type, :stake, :final_date, :final_answer, :answer_type)
    end
end

app/helpers/bets_helper.rb
module BetsHelper
end

app/views/bets/_form.html.erb
<%= form_for(@bet) do |f| %>
  <% if @bet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bet.errors.count, "error") %> prohibited this bet from being saved:</h2>

      <ul>
      <% @bet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :usuario_id %><br>
    <%= f.number_field :usuario_id %>
  </div>
  <div class="field">
    <%= f.label :url_photo %><br>
    <%= f.text_field :url_photo %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :room_status %><br>
    <%= f.number_field :room_status %>
  </div>
  <div class="field">
    <%= f.label :room_type %><br>
    <%= f.number_field :room_type %>
  </div>
  <div class="field">
    <%= f.label :stake %><br>
    <%= f.number_field :stake %>
  </div>
  <div class="field">
    <%= f.label :final_date %><br>
    <%= f.date_select :final_date %>
  </div>
  <div class="field">
    <%= f.label :final_answer %><br>
    <%= f.text_field :final_answer %>
  </div>
  <div class="field">
    <%= f.label :answer_type %><br>
    <%= f.text_field :answer_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bets/edit.html.erb
<%= render "layouts/header" %>
<div class="row">
	<div class="col-lg-8">
		<legend>Edição de uma Aposta</legend>
		<%= form_for(@bet) do |f| %>
		<% if @bet.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@bet.errors.count, "error") %> prohibited this bet from being saved:</h2>
			<ul>
				<% @bet.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		</div>
		<% end %>
		<div class="col-lg-6">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h2 class="panel-title">Dados Gerais da Sala</h2>
				</div>
				<div class="panel-body">
					<div class="form-group">
						<%= f.label :name, "Nome" %><br>
						<%= f.text_field :name, class: "form-control", :required => true %>
					</div>
					<div class="form-group">
						<%= f.label :description, "Descrição" %><br>
						<%= f.text_area :description, class: "form-control", :required => true %>
					</div>
					<div class="field">
						<%= f.label :usuario_id, "Dono da Sala" %><br>
						<div class="input-group">
							<span class="input-group-addon">
							<span class = "glyphicon glyphicon-user"></span>
							</span>
							<% @usuarios = Usuario.all %>
                			<%= f.select :usuario_id, @usuarios.collect{ |usuario| [usuario.name, usuario.id] }, {}, {:class => "form-control", :required => true} %>
						</div>
					</div>
					<div class="form-group">
						<%= f.label :url_photo, "URL da Imagem de Perfil da Sala" %><br>
						<div class="input-group">
							<span class="input-group-addon">
							<span class="glyphicon glyphicon-picture"></span>
							</span>
							<%= f.url_field :url_photo, class: "form-control" %>
						</div>
					</div>
					<div class="form-group">
						<%= f.label :category, "Categoria" %><br>
						<%= f.text_field :category, class: "form-control", :required => true %>
					</div>
					<div class="form-group">
						<%= f.label :stake, "Valor da Aposta (M$)" %><br>
						<div class="input-group">
							<span class="input-group-addon">
							<span class = "glyphicon glyphicon-usd"></span>
							</span>
							<%= f.number_field :stake, class: "form-control" %>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="col-lg-6">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h2 class="panel-title">Manutenção da Sala</h2>
				</div>
				<div class="panel-body">
					<div class="form-group">
						<%= f.label "room_status", "Status da Sala" %><br>
						<%= f.radio_button :room_status, "1", :checked => true %> 
						<%= f.label :room_status, "Ativa", :value => "1" %> &nbsp;
						<%= f.radio_button :room_status, "0" %> 
						<%= f.label :room_status, "Inativa", :value => "0"%>
					</div>
					<div class="form-group">
						<%= f.label "room_type", "Tipo de Sala" %><br>
						<%= f.radio_button :room_type, "1", :checked => true %> 
						<%= f.label :room_type, "Pública", :value => "1" %> &nbsp;
						<%= f.radio_button :room_type, "0" %> 
						<%= f.label :room_type, "Privada", :value => "0"%>
					</div>
					<div class="form-group">
						<%= f.label :final_date, "Data limite para apostas" %><br>
						<%= f.date_field :final_date, :required => true %>
					</div>
					<div class="form-group">
						<%= f.label :final_answer, "Resposta Final" %><br>
						<%= f.text_field :final_answer, class: "form-control" %>
					</div>
					<div class="form-group">
						<%= f.label :answer_type, "Tipo de Resposta" %><br>
						<%= f.select :answer_type, [["Texto","0"], ["Número","1"], ["Data","2"]], {}, {class: "form-control", :required => true} %>
					</div>
				</div>
			</div>
		</div>
		<div class="col-lg-12">
			<div class="actions">
				<%= f.submit "Atualizar", class: "btn btn-primary" %>
			</div>
			<br>
			<%= link_to @bet do %>
			<span class='glyphicon glyphicon-share'></span>&nbsp;Visualizar
			<% end %> | 
			<%= link_to bets_path do %>
			<span class='glyphicon glyphicon-chevron-left'></span>&nbsp;Voltar
			<% end %>
		</div>
		<% end %>
	</div>
</div>
<%= render "layouts/footer" %>

app/views/bets/in.html.erb
<%= render "layouts/header" %>



<%= render "layouts/footer" %>

app/views/bets/index.html.erb
<%= render "layouts/header" %>
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-lg-12">
  
    <legend>Salas de Apostas</legend>
    
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Nome da Sala</th>
          <th>Descrição</th>
          <th>Dono da Sala</th>
          <th>Categoria</th>
          <th>Status da Sala</th>
          <th>Tipo de Sala</th>
          <th>Data limite para apostas</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    
      <tbody>
        <% @bets.each do |bet| %>
          <tr>
            <td><%= bet.name.to_s.force_encoding("UTF-8") %></td>
            <td><%= bet.description.to_s.force_encoding("UTF-8") %></td>
            <% user = Usuario.find(bet.usuario_id) %>
            <td><%= user.name %></td>
            <td><%= bet.category %></td>
            <td>
              <% if bet.room_status == 0 %>
                Inativa
              <% else %>
                Ativa
              <% end %>
            </td>
            <td>
              <% if bet.room_type == 0 %>
                Privada
              <% else %>
                Pública
              <% end %>
            </td>
            <td><%= bet.final_date %></td>
            <td>
              <%= link_to bet, title: "Visualizar" do %>
                <span class='glyphicon glyphicon-eye-open'></span>
              <% end %>
            </td>
            <td>
                <%= link_to edit_bet_path(bet), title: "Editar" do %>
                  <span class='glyphicon glyphicon-edit'></span>
                <% end %>
            </td>
            <td>
                <%= link_to bet, method: :delete, data: { confirm: 'Tem certeza que deseja excluir esta sala?' }, title: "Excluir Sala" do %>
                  <span class='glyphicon glyphicon-trash'></span>
                <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    
    <br>
    
    <%= link_to new_bet_path do %>
      <span class='glyphicon glyphicon-plus-sign'></span>&nbsp;Nova Sala de Apostas
    <% end %>
  
  </div>
</div>
<%= render "layouts/footer" %>

app/views/bets/inside_bet.html.erb
<%= render "layouts/header" %>
		<div></div>
<div class="bloco-titulo col-lg-12"><h2>Bem Vindo a Sala: <%= @bet.name %> </h2></div>
<br><br>
    <div class="panel panel-default" style=" transform: translate(40px,40%); margin-right:20px;float:left;width:45%;overflow:hidden; ">
        <div class="panel-heading"><h2 class="panel-title">Guesses</h2></div>
        <div class="panel-body" >
            <table class="table table-hover" >
                 
                  <thead>
                    <tr>
                      <th>Bet </th>
                      <th>Usuario</th>
                      <th>Won status</th>
                      <th>Guess</th>
                      <th>Status</th>
                      <th colspan="3"></th>
                    </tr>
                  </thead>
            
                  <tbody>
                    <% Guess.where(:bet_id => @bet.id).find_each do |guess| %>
                      <tr>
                        <td><%= guess.bet_id %></td>
                        <td><%= guess.usuario_id %></td>
                        <td><%= guess.won_status %></td>
                        <td><%= guess.guess_text %></td>
                        <td><%= guess.guess_status %></td>
                        
                      </tr>
                    <% end %>
                  </tbody>
            </table>
        </div>
    </div>
    <div class="panel  panel-primary" style="margin-bottom: 20px; margin-left:100px;float:left;width:45%;overflow:hidden; ">
        <div class="panel-heading"style="background-color: baby blue;"><h2 class="panel-title">Sobre a Sala</h2></div>
        <div class="panel-body" >
          <p>
							<strong>Nome:</strong>
							<%= @bet.name %>
						</p>
						<p>
							<strong>Descrição:</strong>
							<%= @bet.description %>
						</p>
						<p>
							<strong>Dono da Sala:</strong>
							<% user = Usuario.find(@bet.usuario_id) %>
							<%= user.name %>
						</p>
						<p>
							<strong>Url da foto:</strong>
							<%= @bet.url_photo %>
						</p>
						<p>
							<strong>Categoria:</strong>
							<%= @bet.category %>
						</p>
						<p>
							<strong>Valor da aposta:</strong>
							<%= @bet.stake %>
						</p>
        </div>
    </div>
    <div class="panel  panel-primary" style="transform: translate(-40px,-40%);margin-bottom: 20px; margin-left:100px;float:left;width:40%;overflow:hidden;">
        <div class="panel-heading"style="background-color: baby blue;"><h2 class="panel-title">Participantes</h2></div>
        <div class="panel-body" >
          <table width="40%" class="table table-hover" >
                
                  <thead>
                    <tr>
                      <th>Usuarios</th>
                    </tr>
                  </thead>
            
                  <tbody>
                    <% Guess.where(:bet_id => @bet.id).find_each do |guess| %>
                        <% Usuario.where(:id => guess.usuario_id).find_each do |usuario| %>
                      <tr>
                         <td><%=usuario.name %></td>
                        
                      </tr>
                      <% end %>
                    <% end %>
                  </tbody>
            </table>
        </div>
    </div>
  


<br><br>
    
<button type="button" class="btn btn-default" style= "margin-top:20px;margin-left: 10px;">
   <%= link_to "Apostar",controller: 'guesses', action: 'new', :bet_id => @bet.id, :usuario_id => session[:user_id]%>
</button> 
<button type="button" class="btn btn-default" style= "margin-top:20px;margin-left: 10px;">
   <%= link_to "Convidar", novo_invite_path(@bet.id) %>
</button> 
<%= render "layouts/footer" %>

app/views/bets/lista.html.erb
<%= render "layouts/header" %>

<legend>Minhas apostas</legend>

<table class="table table-hover">
      <thead>
        <tr>
          <th>Nome da Sala</th>
          <th>Descrição</th>
          <th>Tipo de Sala</th>
          <th>Data limite para apostas</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    <tbody>
        <% @bets.each do |bet| %>
          <tr>
            <td><%= bet.name %></td>
            <td><%= bet.description.to_s.force_encoding("UTF-8") %></td>
            <td>
              <% if bet.room_type == 0 %>
                Privada
              <% else %>
                Pública
              <% end %>
            </td>
            <td><%= bet.final_date %></td>
            <td>
              <%= link_to bet, title: "Visualizar" do %>
                <span class='glyphicon glyphicon-eye-open'></span>
              <% end %>
            </td>
          </tr>
        <% end %>
    </tbody>
</table>

<%= render "layouts/footer" %>

app/views/bets/new.html.erb
<%= render "layouts/header" %>
<div class="row">
  <div class="col-lg-8">
  
    <legend>Nova Sala de Apostas</legend>
  
    <%= form_for(@bet) do |f| %>
    
      <% if @bet.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@bet.errors.count, "error") %> prohibited this bet from being saved:</h2>
    
          <ul>
          <% @bet.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      
      <div class="col-lg-6">
        <div class="panel panel-default">
          
          <div class="panel-heading">
            <h2 class="panel-title">Dados Gerais da Sala</h2>
          </div>
        
          <div class="panel-body">
            
            <div class="form-group">
              <%= f.label :name, "Nome" %><br>
              <%= f.text_field :name, class: "form-control", :required => true %>
            </div>
            
            <div class="form-group">
              <%= f.label :description, "Descrição" %><br>
              <%= f.text_area :description, class: "form-control", :required => true %>
            </div>
            
            <div class="form-group">
              <%= label "usuario_nome", "Dono da Sala" %><br>
              <div class="input-group">
                <span class="input-group-addon">
                  <span class = "glyphicon glyphicon-user"></span>
                </span>
                <% @usuarios = Usuario.all %>
                <%= f.select :usuario_id, @usuarios.collect{ |usuario| [usuario.name, usuario.id] }, {}, {:class => "form-control", :required => true} %>
                
              </div>
            </div>
            
            <div class="form-group">
              <%= f.label :url_photo, "URL da Imagem de Perfil da Sala" %><br>
              <div class="input-group">
                <span class="input-group-addon">
                  <span class="glyphicon glyphicon-picture"></span>
                </span>
                <%= f.url_field :url_photo, class: "form-control" %>
              </div>
            </div>
            
            <div class="form-group">
              <%= f.label :category, "Categoria" %><br>
              <%= f.text_field :category, class: "form-control", :required => true %>
            </div>
                  
            <div class="form-group">
              <%= f.label :stake, "Valor da Aposta (M$)" %><br>
              <div class="input-group">
                <span class="input-group-addon">
                  <span class = "glyphicon glyphicon-usd"></span>
                </span>
                <%= f.number_field :stake, class: "form-control" %>
              </div>
            </div>
            
          </div>
        </div>
      </div>
      
      <div class="col-lg-6">
        <div class="panel panel-default">
          
          <div class="panel-heading">
            <h2 class="panel-title">Manutenção da Sala</h2>
          </div>
        
          <div class="panel-body">
      
            <div class="form-group">
              <%= f.label "room_status", "Status da Sala" %><br>
                <%= f.radio_button :room_status, "1", :checked => true %> 
                <%= f.label :room_status, "Ativa", :value => "1" %> &nbsp;
                <%= f.radio_button :room_status, "0" %> 
                <%= f.label :room_status, "Inativa", :value => "0"%>
            </div>
            
            <div class="form-group">
              <%= f.label "room_type", "Tipo de Sala" %><br>
                <%= f.radio_button :room_type, "1", :checked => true %> 
                <%= f.label :room_type, "Pública", :value => "1" %> &nbsp;
                <%= f.radio_button :room_type, "0" %> 
                <%= f.label :room_type, "Privada", :value => "0"%>
            </div>
            
            <div class="form-group">
              <%= f.label :final_date, "Data limite para apostas" %><br>
              <%= f.date_field :final_date, :required => true %>
            </div>
            
            <div class="form-group">
              <%= f.label :final_answer, "Resposta Final" %><br>
              <%= f.text_field :final_answer, class: "form-control", :disabled => true %>
            </div>
            
            <div class="form-group">
              <%= f.label :answer_type, "Tipo de Resposta" %><br>
              <%= f.select :answer_type, [["Texto","0"], ["Número","1"], ["Data","2"]], {}, {class: "form-control", :required => true} %>
            </div>
            
          </div>
        </div>
      </div>
    
      <div class="col-lg-12">
        <div class="actions">
          <%= f.submit "Cadastrar", class: "btn btn-primary" %>
        </div>  
        
        <br>
        
        <%= link_to bets_path do %>
          <span class='glyphicon glyphicon-chevron-left'></span>&nbsp;Voltar
        <% end %>
      </div>
    
    <% end %>
  
  </div>
</div>
<%= render "layouts/footer" %>

app/views/bets/nova.html.erb
<%= render "layouts/header" %>
<div class="row">
    <div class="col-lg-4">
      
      <legend>Nova Sala de Apostas</legend>
      
      <%= form_for @bet, url: {controller: "bets", action: "bet_create"} do |f| %>
      <% if @bet.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@bet.errors.count, "error") %> prohibited this bet from being saved:</h2>
    
          <ul>
          <% @bet.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
    
      <div class="form-group">
        <label for="Nome">Nome: </label><br>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      
      <div class = "form-group">
        <label for="Descrição">Descrição: </label><br>
          <%= f.text_area :description, class: "form-control" %>
      </div>
    
      <div class="form-group">
        <label for="Foto">Link para foto de perfil da sala: </label><br>
        <div class="input-group">
          <span class="input-group-addon">
            <span class="glyphicon glyphicon-picture"></span>
          </span>
          <%= f.text_field :url_photo, class: "form-control" %>
        </div>
      </div>
      
      <div class="form-group">
        <%= f.label "room_type", "Tipo de Sala:" %><br>
          <%= f.radio_button :room_type, "1", :checked => true %> 
          <%= f.label :room_type, "Pública", :value => "1" %> &nbsp;
          <%= f.radio_button :room_type, "0" %> 
          <%= f.label :room_type, "Privada", :value => "0"%>
      </div>
      
      <div class="form-group">
        <label  for="Valor apostado">Valor apostado: </label><br>
        
        <div class="input-group">
          <span class="input-group-addon">
            <span class = "glyphicon glyphicon-usd"></span>
          </span>
          <%= f.number_field :stake, class: "form-control" %>
        </div>
      </div>
     
      <div class="actions">
        <%= f.submit "Criar aposta", class: "btn btn-primary", id: "criarBtn" %>
      </div>
      
      <% end %>
      
      <br>
      
      <%= link_to controller: "welcome", action: "painel" do %>
        <span class='glyphicon glyphicon-chevron-left'></span>&nbsp;Voltar
      <% end %>
      
    </div>
</div>
<%= render "layouts/footer" %>

app/views/bets/show.html.erb
<%= render "layouts/header" %>
<p id="notice"><%= notice %></p>
<div class="row">
	<div class="col-lg-12">
		<legend>Dados da Aposta</legend>
		<div class="row">
			<div class="col-lg-4">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h2 class="panel-title">Aposta</h2>
					</div>
					<div class="panel-body">
						<p>
							<strong>Nome:</strong>
							<%= @bet.name %>
						</p>
						<p>
							<strong>Descrição:</strong>
							<%= @bet.description %>
						</p>
						<p>
							<strong>Dono da Sala:</strong>
							<% user = Usuario.find(@bet.usuario_id) %>
							<%= user.name %>
						</p>
						<p>
							<strong>Url da foto:</strong>
							<%= @bet.url_photo %>
						</p>
						<p>
							<strong>Categoria:</strong>
							<%= @bet.category %>
						</p>
						<p>
							<strong>Valor da aposta:</strong>
							<%= @bet.stake %>
						</p>
					</div>
				</div>
			</div>
			<div class="col-lg-4">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h2 class="panel-title">Informações Gerais:</h2>
					</div>
					<div class="panel-body">
						<p>
							<strong>Status da Sala:</strong>
							<% if @bet.room_status == 0 %>
							Inativa
							<% else %>
							Ativa
							<% end %>
						</p>
						<p>
							<strong>Tipo da Sala:</strong>
							<% if @bet.room_type == 0 %>
							Privada
							<% else %>
							Pública
							<% end %>
						</p>
						<p>
							<strong>Data limite para apostas:</strong>
							<%= @bet.final_date %>
						</p>
						<p>
							<strong>Resposta Final:</strong>
							<%= @bet.final_answer %>
						</p>
						<p>
							<strong>Tipo de Resposta:</strong>
							<%= @bet.answer_type %> <!-- Corrigir -->
						</p>
					</div>
				</div>
			</div>
		</div>
		<%= link_to edit_bet_path(@bet) do %>
		<span class='glyphicon glyphicon-edit'></span>&nbsp;Editar
		<% end %>
		|
		<%= link_to bets_path do %>
		<span class='glyphicon glyphicon-chevron-left'></span>&nbsp;Voltar
		<% end %>
		|
		<%= link_to controller: "bets", action:'inside_bet', :id => @bet do %>
		<span class='glyphicon glyphicon-log-in'></span>&nbsp;Entrar na aposta
		<% end %>
		
		<!--
			<button type="button" class="btn "><%= link_to 'Entrar na Aposta', controller: "bets", action:'inside_bet', :id => @bet%>
			</button> 
			-->
	</div>
</div>
<%= render "layouts/footer" %>