config/routes.rb
Rails.application.routes.draw do
  get "/invites/:id_bet/novo" => "invites#novo", as: "novo_invite"
  get "/invites/inserir" => "invites#inserir", as: "inserir"
  resources :invites
  resources :guesses
  resources :bets
  get "/apostas/nova" => "bets#nova"
  post "/apostas/nova" => "bets#bet_create"
  get "/apostas/inside_bet" => "bets#inside_bet"
  post "/apostas/inside_bet" => "bets#inside_bet"
  get "/bets/" => "bets#inside_bet"
  get "/guesses/nova" => "guesses#nova"
  post "/guesses/nova" => "guesses#guess_create"
  post "/usuarios/login" => "usuarios#login"
  get "/usuarios/cadastro" => "usuarios#cadastro"
  get "/painel" => "welcome#painel"
  get "/usuarios_srch" => "invites#usuarios_srch", as: 'usuarios_srch'
  post "/usuarios/cadastro" => "usuarios#cadastro_create"
  resources :usuarios
  get "/auth/:provider/callback" => "sessions#create", as: :auth_callback
  get "/auth/failure" => "sessions#failure", as: :auth_failure
  get "/logout" => "sessions#destroy", as: :logout
  get 'welcome/index'
  resources :widgets
  get "/apostas/minhas" => "bets#lista"

  root 'welcome#index'
  
  resources :dialogos do
    resources :postagems
end

end

app/controllers/guesses_controller.rb
class GuessesController < ApplicationController
  before_action :set_guess, only: [:show, :edit, :update, :destroy]

  # GET /guesses
  # GET /guesses.json
  def index
    @guesses = Guess.all
  end

  # GET /guesses/1
  # GET /guesses/1.json
  def show
  end

  # GET /guesses/new
  def new
    @guess = Guess.new
  end

  # GET /guesses/1/edit
  def edit
  end

  # POST /guesses
  # POST /guesses.json
  def create
    @guess = Guess.new(guess_params)

    respond_to do |format|
      if @guess.save
        format.html { redirect_to @guess, notice: 'Guess was successfully created.' }
        format.json { render :show, status: :created, location: @guess }
      else
        format.html { render :new }
        format.json { render json: @guess.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guesses/1
  # PATCH/PUT /guesses/1.json
  def update
    respond_to do |format|
      if @guess.update(guess_params)
        format.html { redirect_to @guess, notice: 'Guess was successfully updated.' }
        format.json { render :show, status: :ok, location: @guess }
      else
        format.html { render :edit }
        format.json { render json: @guess.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guesses/1
  # DELETE /guesses/1.json
  def destroy
    @guess.destroy
    respond_to do |format|
      format.html { redirect_to guesses_url, notice: 'Guess was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guess
      @guess = Guess.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def guess_params
      params.require(:guess).permit(:bet_id, :usuario_id, :won_status, :guess_text, :guess_status)
    end
end

app/helpers/guesses_helper.rb
module GuessesHelper
end

app/views/guesses/_form.html.erb
<%= form_for(@guess) do |f| %>
  <% if @guess.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@guess.errors.count, "error") %> prohibited this guess from being saved:</h2>

      <ul>
      <% @guess.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :bet_id %><br>
    <%= f.number_field :bet_id %>
  </div>
  <div class="field">
    <%= f.label :usuario_id %><br>
    <%= f.number_field :usuario_id %>
  </div>
  <div class="field">
    <%= f.label :won_status %><br>
    <%= f.check_box :won_status %>
  </div>
  <div class="field">
    <%= f.label :guess_text %><br>
    <%= f.text_field :guess_text %>
  </div>
  <div class="field">
    <%= f.label :guess_status %><br>
    <%= f.number_field :guess_status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/guesses/edit.html.erb
<h1>Editing Guess</h1>

<%= render 'form' %>

<%= link_to 'Show', @guess %> |
<%= link_to 'Back', guesses_path %>

app/views/guesses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Guesses</h1>

<table>
  <thead>
    <tr>
      <th>Bet</th>
      <th>Usuario</th>
      <th>Won status</th>
      <th>Guess text</th>
      <th>Guess status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @guesses.each do |guess| %>
      <tr>
        <td><%= guess.bet_id %></td>
        <td><%= guess.usuario_id %></td>
        <td><%= guess.won_status %></td>
        <td><%= guess.guess_text %></td>
        <td><%= guess.guess_status %></td>
        <td><%= link_to 'Show', guess %></td>
        <td><%= link_to 'Edit', edit_guess_path(guess) %></td>
        <td><%= link_to 'Destroy', guess, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Guess', new_guess_path %>

app/views/guesses/new.html.erb
<%= render "layouts/header" %>
<div class="row">
    <div class="col-lg-4">
      
      <legend style="text-align:center">Nova Apostas</legend>
        <div class="panel  panel-primary" style="margin:auto;width:40%;overflow:hidden; ">
        <div class="panel-heading"style="background-color: baby blue;"><h2 class="panel-title">Participantes</h2></div>
        <div class="panel-body", style="margin:auto;width:45%;" >
            <!-- queria colocar = Usuario.find(session[:user_id]).name %>, o rakepec me impede-->
          <p> Olá, por favor insira seu palpite.</p>
            <%= form_for(@guess) do |f| %>
              <% if @guess.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@guess.errors.count, "error") %> prohibited this guess from being saved:</h2>
            
                  <ul>
                  <% @guess.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                  </ul>
                </div>
              <% end %>
            
              <div class="field">
                <%= f.label :bet_id %><br>
                <%= f.number_field :bet_id , :value => params[:bet_id], :readonly =>true  %>
              </div>
              <div class="field">
                <%= f.label :usuario_id %><br>
                <%= f.number_field :usuario_id , :value => params[:usuario_id], :readonly =>true  %>
              </div>
              <div class="field">
                <%= f.label :won_status %><br>
                <%= f.check_box :won_status, :value => false, :readonly =>true %>
              </div>
              <div class="field">
                <%= f.label :guess_text %><br>
                <%= f.text_field :guess_text %>
              </div>
              
              <div class="field">
                <%= f.label :guess_status %><br>
                <%= f.number_field :guess_status %>
              </div>
              
              <div class="actions" style = "margin-top: 20px;">
                <%= f.submit "Palpitar" %>
              </div>
            <% end %>
            
            </div>
        </div>
    </div>
</div>
<div style = "maginl-left: 300px"> <%= link_to guesses_path do %>
		<span class='glyphicon glyphicon-chevron-left'></span>&nbsp;Voltar
		<% end %>
</div>

<%= render "layouts/footer" %>

app/views/guesses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bet:</strong>
  <%= @guess.bet_id %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @guess.usuario_id %>
</p>

<p>
  <strong>Won status:</strong>
  <%= @guess.won_status %>
</p>

<p>
  <strong>Guess text:</strong>
  <%= @guess.guess_text %>
</p>

<p>
  <strong>Guess status:</strong>
  <%= @guess.guess_status %>
</p>

<%= link_to 'Edit', edit_guess_path(@guess) %> |
<%= link_to 'Back', guesses_path %>