config/routes.rb
Rails.application.routes.draw do
  get "/invites/:id_bet/novo" => "invites#novo", as: "novo_invite"
  get "/invites/inserir" => "invites#inserir", as: "inserir"
  resources :invites
  resources :guesses
  resources :bets
  get "/apostas/nova" => "bets#nova"
  post "/apostas/nova" => "bets#bet_create"
  get "/apostas/inside_bet" => "bets#inside_bet"
  post "/apostas/inside_bet" => "bets#inside_bet"
  get "/bets/" => "bets#inside_bet"
  get "/guesses/nova" => "guesses#nova"
  post "/guesses/nova" => "guesses#guess_create"
  post "/usuarios/login" => "usuarios#login"
  get "/usuarios/cadastro" => "usuarios#cadastro"
  get "/painel" => "welcome#painel"
  get "/usuarios_srch" => "invites#usuarios_srch", as: 'usuarios_srch'
  post "/usuarios/cadastro" => "usuarios#cadastro_create"
  resources :usuarios
  get "/auth/:provider/callback" => "sessions#create", as: :auth_callback
  get "/auth/failure" => "sessions#failure", as: :auth_failure
  get "/logout" => "sessions#destroy", as: :logout
  get 'welcome/index'
  resources :widgets
  get "/apostas/minhas" => "bets#lista"

  root 'welcome#index'
  
  resources :dialogos do
    resources :postagems
end

end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
    schema_validations auto_create: false
	def self.find_or_create_with_omniauth(auth)
		
		usuario = self.find_or_initialize_by(provider: auth.provider, uid: auth.uid)
		
		usuario.assign_attributes({ name: auth.info.name, email: auth.info.email, photo_url: auth.info.image, access_token: auth.credentials.token, status: true, user_type: "2", data_ingresso: Time.now})
		usuario.save
		
		usuario
	end
	
	def self.search(search)
	   
	   if(search)
	       where('name LIKE ? AND status = ? AND user_type = ?', "%#{search}%", true, '2')
	   else
	       where('status = ? AND user_type = ?', true, '2') 
	   end
	end
    
    validates :name, presence: true
    validates :email, presence: true, email: true, uniqueness: true #Melhorar verificacao (melhor opcao eh enviar um email - n usar regex)
    validates :access_token, presence: true
    validates :uid, presence: true, if: :signed_with_facebook?
    validates :user_type, presence: true #revisar verificacao (por conta dos testes gerados automaticamente)
    
    #verificao certa, trava num dos testes automaticos pq ele usa "myString"
    #validates :user_type, format: {with: /[1,2]/} 
    
    
    #Funcao que testa se o cadastro foi feito pelo fb
    private
    def signed_with_facebook?
    	provider == "facebook"
    end
    
    has_many :bets, class_name: 'Bet', foreign_key: 'usuario_id', dependent: :destroy
    has_many :invites
    
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
    
    if params[:search]
      @usuarios = Usuario.search(params[:search])
    else
      @usuarios = Usuario.all.order('created_at ASC')
    end
  end
  
  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end
  
  # POST /usuarios/login
  def login
	
  	@usuario = Usuario.find_by(email: usuario_params[:email], provider: "email")
  	
  	if @usuario == nil
  		redirect_to controller: 'welcome', action: 'index', :notice => "Falha ao logar"
  	else
  		if @usuario.access_token == usuario_params[:access_token]
  			session[:user_id] = @usuario.id
  			redirect_to controller: 'welcome', action: 'painel', :notice => "Bem vindo"
  		else
  			redirect_to controller: 'welcome', action: 'index', :notice => "Falha ao logar"
  		end
  	end
  end
  
  # GET /usuarios/cadastro
  def cadastro
  	@usuario = Usuario.new
  end
  
  # POST /usuarios/cadastro_create
  def cadastro_create
  	@usuario = Usuario.new(usuario_params)
  	@usuario.provider = "email"
  	@usuario.status = true
  	@usuario.user_type = "2"
  	@usuario.data_ingresso = Time.now
  	
    respond_to do |format|
      if @usuario.save
        session[:user_id] = @usuario.id
        format.html { redirect_to controller: 'welcome', action: 'painel', notice: 'Usuario was successfully created.' }
        #format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :cadastro }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end
  

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:name, :email, :access_token, :uid, :photo_url, :provider, :status, :reason, :user_type, :data_ingresso)
    end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/usuarios/_form.html.erb
<%= form_for(@usuario) do |f| %>

  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% @usuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-lg-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2 class="panel-title">Dados do Usuário</h2>
      </div>
      
      <div class="panel-body">
  
        <div class="form-group">
          <%= f.label :name, "Nome" %><br>
          <%= f.text_field :name, class: "form-control", :required => true %>
        </div>
        
        <div class="form-group">
          <%= f.label :email, "E-mail" %><br>
          <div class="input-group">
            <span class="input-group-addon">@</span>
            <%= f.text_field :email, type: "email", class: "form-control", :required => true %>
          </div>
        </div>
        
        <% if @usuario.provider == "email" %>
        
          <div class="form-group">
            <%= f.label :access_token, "Senha" %><br>
            <%= f.password_field :access_token, class: "form-control", :required => true, value: @usuario.access_token %>
          </div>
          
          <div class="form-group">
            <%= f.label "confirmar", "Confirmar Senha" %><br>
            <%= f.password_field "confirmar", class: "form-control", :required => true, value: @usuario.access_token %>
          </div>
        
        <% end %>
        
        <div class="form-group">
          <%= f.label "provider", "Tipo de Acesso" %><br>
          <%= f.hidden_field :provider %>
          <% if @usuario.provider == "email" %>
            E-mail
          <% else %>
            Facebook
          <% end %>
        </div>
        
        <div class="form_group">
          <b>Data de Ingresso</b><br>
          <%= @usuario.created_at.strftime "%d/%m/%Y %H:%M:%S" %><br>
          
          <br>
          
          <b>Última alteração</b><br>
          <%= @usuario.updated_at.strftime "%d/%m/%Y %H:%M:%S" %>
        </div>
        
      </div>
    </div>
    
  </div>
  
  <div class="col-lg-4">
    
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2 class="panel-title">Manutenção Usuário</h2>
      </div>
      
      <div class="panel-body">
        
        <div class="form-group">
          <%= f.check_box :status %> <%= f.label :status, "Usuário Ativo" %><br>
        </div>
        
        <div class="form-group">
          <%= f.label :reason, "Motivo (em caso de inativação)" %><br>
          <%= f.text_field :reason, class: "form-control" %>
        </div>
        
        <div class="form-group">
            <%= f.label "user_type", "Tipo de Usuário" %><br>
              <%= f.radio_button :user_type, "1", :checked => true %> 
              <%= f.label :user_type, "Administrador", :value => "1" %> &nbsp;
              <%= f.radio_button :user_type, "2" %> 
              <%= f.label :user_type, "Apostador", :value => "2"%>
        </div>
      
      </div>
      
    </div>
  
  </div>
  
  <div class="col-lg-4">
    
    <% if @usuario.provider == "facebook" %>
    
      <div class="panel panel-default">
        <div class="panel-heading">
          <h2 class="panel-title">Dados do Facebook</h2>
        </div>
        
        <div class="panel-body">
          
          <div class="form-group">
            <%= f.label :uid, "UiD" %><br>
            <%= f.text_field :uid, class: "form-control", :required => true %>
          </div>
          
          <div class="form-group">
            <%= f.label :access_token, "Token de Acesso" %><br>
            <%= f.text_field :access_token, class: "form-control", :required => true %>
          </div>
          
          <div class="form-group">
            <%= f.label :photo_url, "Foto de Perfil" %><br>
            <%= f.hidden_field :photo_url %>
            <%= image_tag(@usuario.photo_url) %>
          </div>
          
        </div>
      </div>
    
    <% end %>
        
  </div>

  <div class="col-lg-12">
    <div class="actions">
       <%= f.submit "Atualizar", class: "btn btn-primary", id: "atualiza_btn" %>
       <br>&nbsp;<br>
    </div>
  </div>

<% end %>

app/views/usuarios/cadastro.html.erb
<p id="notice"><%= notice %></p>
<div class="full-width full-height" >
   <div class="full-width full-height" id="banner-bloco-home">
    <div class="full-width full-height" id="cor-preto-bloco-home">
     <div class="full-width full-height" id="gradient-white">
     
      <div class="card-bloco-home-center">
       <div class="bloco-box-cadastro">
        <p class="titulo-box-bloco-cadastro">Cadastre-se</p>
        <br>
         <div class= "caixa-banner-bloco-home">
           
           <%= form_for @usuario, url: {controller: "usuarios", action: "cadastro_create"} do |f| %>
                    <% if @usuario.errors.any? %>
                      <div id="error_explanation">
                        <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>
                  
                        <ul>
                        <% @usuario.errors.full_messages.each do |message| %>
                          <li><%= message %></li>
                        <% end %>
                        </ul>
                      </div>
                    <% end %>
                    
                   <br>
                    <div class="field">
                    <label class="lbl-cadastro" for="Nome">Nome:  </label>
                      <%= f.text_field :name , :class=>"input-login-page"%>
                    </div>
                    
                   <br>
                    <div class="field">
                    <label class="lbl-cadastro" for="E-mail">Email:  </label>
                      <%= f.text_field :email , :class=>"input-login-page"%>
                    </div>
                    <br>
                    
                    <div class="field">
                      <label class="lbl-cadastro" for="senha">Senha:  </label>
               <%= f.password_field :access_token,  :class=>"input-login-page"%>
                    </div>
					
                    <div class="actions float-right">
                        <%= f.submit "Cadastrar", :class=>"btn-cadastro", :id=>"button_cad" %>
                    </div>
                    
                  <% end %>
      
        </div>
       </div>
      </div>
     </div>
    </div>
   </div>
  </div>

app/views/usuarios/edit.html.erb
<%= render "layouts/header" %>
<p id="notice"><%= notice %></p>

<div class="row">
    <div class="col-lg-12">
        <div class="row"></div>
    
            <legend>Alterar Usuário</legend>
            
            <%= render 'form' %>
            
            <div class="col-lg-12">
                <%= link_to @usuario do %>
                    <span class="glyphicon glyphicon-share"></span>&nbsp;Visualizar
                <% end %> |
                
                <%= link_to usuarios_path do %>
                    <span class='glyphicon glyphicon-chevron-left'></span>&nbsp;Voltar
                <% end %>
            </div>
        
        </div>
    </div>
</div>

<%= render "layouts/footer" %>

app/views/usuarios/footer.html.erb
<div class="footer">
	<div class="logout">
	</div>
</div>

app/views/usuarios/header.html.erb
<div class="header">
	<div class="logo">
	</div>
	<div class="titulo">
		<p class="lbl-header">Dobro ou Nada</p>
	</div>
</div>

app/views/usuarios/index.html.erb
<%= render "layouts/header" %>
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-lg-9">
    
    <legend>Usuários</legend>
  
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Id</th>
          <th>Nome</th>
          <th>E-mail</th>
          <th>Tipo de Login</th>
          <th>Status</th>
          <th>Tipo</th>
          <th>Data ingresso</th>
          <th colspan="2"></th>
        </tr>
      </thead>
    
      <tbody>
        <% @usuarios.each do |usuario| %>
          <tr>
            <td><%= usuario.id %></td>
            <td><%= usuario.name %></td>
            <td><%= usuario.email %></td>
            <td><%= if usuario.provider == "email"
                      "E-mail"
                    else
                      "Facebook"
                    end
                %></td>
            <td><%= if usuario.status
                      "Ativo"
                    else
                      "Inativo"
                    end
                %></td>
            <td><%= if usuario.user_type == "1"
                      "Administrador"
                    else
                      "Apostador"
                    end 
                %></td>
            <td><%= usuario.created_at.strftime "%d/%m/%Y" %></td>
            <td>
              <%= link_to usuario, title: "Visualizar", id: "visu" << usuario.id.to_s do %>
              <%=   content_tag(:span, '',:class=>'glyphicon glyphicon-share') %>
              <% end %>
            </td>
            <td>
                <%= link_to edit_usuario_path(usuario), title: "Editar", id: "edit" << usuario.id.to_s do %>
                  <%=   content_tag(:span, '',:class=>'glyphicon glyphicon-edit') %>
                <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  
    <%= link_to new_usuario_path do %>
      <span class='glyphicon glyphicon-plus-sign'></span>&nbsp;Novo Usuário
    <% end %>
  
  </div>
</div>

<%= render "layouts/footer" %>

app/views/usuarios/new.html.erb
<%= render "layouts/header" %>

<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-lg-4">
    
    <legend>Novo Usuário</legend>
    
    <%= form_for(@usuario) do |f| %>
    
      <% if @usuario.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>
    
          <ul>
          <% @usuario.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
    
      <div class="form-group">
        <%= f.label :name, "Nome" %><br>
        <%= f.text_field :name, class: "form-control", :required => true %>
      </div>
      
      <div class="form-group">
        <%= f.label :email, "E-mail" %><br>
        <div class="input-group">
          <span class="input-group-addon">@</span>
          <%= f.text_field :email, type: "email", class: "form-control", :required => true %>
        </div>
      </div>
      
      <div class="form-group">
        <%= f.label :access_token, "Senha" %><br>
        <%= f.password_field :access_token, class: "form-control", :required => true %>
      </div>
      
      <div class="form-group">
        <%= f.label "confirmar", "Confirmar Senha" %><br>
        <%= f.password_field "confirmar", class: "form-control", :required => true %>
      </div>
      
      <%= f.hidden_field :provider, value: "email" %>
      <%= f.hidden_field :status, value: "true" %>
      
      <div class="form-group">
          <%= f.label "user_type", "Tipo de Usuário" %><br>
            <%= f.radio_button :user_type, "1", :checked => true %> 
            <%= f.label :user_type, "Administrador", :value => "1" %> &nbsp;
            <%= f.radio_button :user_type, "2" %> 
            <%= f.label :user_type, "Apostador", :value => "2"%>
      </div>
      
      <div class="actions">
        <%= f.submit "Cadastrar", class: "btn btn-primary" %>
      </div>
      
    <% end %>
  
      <br>
      
      <%= link_to usuarios_path do %>
        <span class='glyphicon glyphicon-chevron-left'></span>&nbsp;Voltar
      <% end %>
  
  </div>
</div>
<%= render "layouts/footer" %>

app/views/usuarios/show.html.erb
<%= render "layouts/header" %>
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-lg-12">
    
    <legend>Dados do Usuário</legend>
    
    <div class-"row">
      
      <div class="col-lg-4">
        
        <div class="panel panel-default">
          <div class="panel-heading">
            <h2 class="panel-title">Dados do Usuário</h2>
          </div>
          
          <div class="panel-body">
  
            <p>
              <strong>Nome:</strong>
              <%= @usuario.name %>
            </p>
  
            <p>
              <strong>E-mail:</strong>
              <%= @usuario.email %>
            </p>
            
            <p>
              <strong>Tipo de Acesso:</strong>
              <% if @usuario.provider == "email" %>
                E-mail
              <% else %>
                Facebook
              <% end %>
            </p>
  
            <p>
              <strong>Data ingresso:</strong>
              <%= @usuario.created_at %>
            </p>
            
            <p>
              <strong>Última Alteração:</strong>
              <%= @usuario.updated_at %>
            </p>
          
          </div>
        </div>
        
      </div>
      <div class="col-lg-4">
        
        <div class="panel panel-default">
          <div class="panel-heading">
            <h2 class="panel-title">Manutenção Usuário</h2>
          </div>
          
          <div class="panel-body">
            
            <p>
              <strong>Tipo de Usuário:</strong>
              <% if @usuario.user_type == "1" %>
                Administrador
              <% else %>
                Apostador
              <% end %>
            </p>
            
            <p>
              <strong>Status:</strong>
              <% if @usuario.status %>
                Ativo
              <% else %>
                Inativo
              <% end %>
            </p>
            
            <p>
              <strong>Motivo:</strong>
              <%= @usuario.reason %>
            </p>
          
          </div>
        </div>
      </div>
        
      <% if @usuario.provider == "facebook" %>
      <div class="col-lg-4">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h2 class="panel-title">Dados do Facebook</h2>
          </div>
          
          <div class="panel-body">
            
            <p>
              <strong>UiD:</strong>
              <%= @usuario.uid %>
            </p>
            
            <p>
              <strong>Foto de Perfil:</strong><br>
              <%= image_tag(@usuario.photo_url) %>
            </p>
            
          </div>
        </div>
      </div>
      <% end %>
        
    </div>
  </div>
  
  <div class="col-lg-12">
    
    <%= link_to edit_usuario_path(@usuario) do %>
      <span class='glyphicon glyphicon-edit'></span>&nbsp;Alterar
    <% end %>
    
    |
    
    <%= link_to usuarios_path do %>
      <span class='glyphicon glyphicon-chevron-left'></span>&nbsp;Voltar
    <% end %>
    
  </div>
</div>  
  
<%= render "layouts/footer" %>